feat: Added Stacked Bar Graph
chaaals/da-project-frontend pull request #42
Opened 2024-12-02 15:33 UTC by uzuriel

- Has legends above the chart

Needed props for the component:
- data to be displayed
- keys 
- color

2024-12-02 15:45 UTC, chaaals requested changes
lgtm, altho, ginagamit ba topojson?

2024-12-02 15:45 UTC, chaaals commented on package.json
> +    "topojson-client": "^3.1.0"
uninstall topojson for this pr

2024-12-03 09:18 UTC, uzuriel commented
Uh nooo, i forgot to remove it in packages

2024-12-03 13:55 UTC, chaaals approved these changes

2024-12-03 13:55 UTC, merged